goose_dbstring: user=admin password=admin dbname=service sslmode=disable
goose_driver: postgres
goose_migration_dir: migrations
postgres_connection_host: postgres
postgres_database: service
postgres_password: admin
postgres_port: "5432"
postgres_sslmode_enabled: "false"
postgres_user: admin
server_address: :8000
server_idle_timeout: 3s
server_read_timeout: 5s
server_shutdown_duration: 5s
server_write_timeout: 5s
